spring.application.name=bai6_springsecurity
spring.datasource.url=jdbc:mysql://localhost:3306/bai6_security
spring.datasource.username=root
spring.datasource.password=#Anhcute36
spring.jpa.hibernate.ddl-auto=update

